import os
os.environ["TOKEN_URL"] = "https://identity.bankURL/identity/oauth2/auth/token"
os.environ["STATEMENT_URL"] = "https://account.bankURL/api/mq-statement/v2/online-statement"
os.environ["STATEMENT_COOKIE"] = "cookiesession1=1234"
os.environ["TOKEN_COOKIE"] = "cookiesession1=1234"
os.environ["ACCOUNT_NUMBER"] = ""
os.environ["BASE_DIR"] = ""
os.environ["EMAIL_PASSWORD"] = ""
os.environ["EMAIL_ADDRESS"] = ""
os.environ["DESTINATION_EMAIL"] = "example@gmail.com, example2@gmail.com"